### ISSUE TITLE
aot.tsconfig.json的疑问

### ISSUE THREAD

**Issue by keyiis** [ntesmail/angular-webpack-template#1]
看到包主使用了@ngtool/webpack,为何还要在aot.tsconfig.json中设置genDir?@ngtool/webpack应该会在内存中进行编译并替换bootstrap,我项目中的配置和你差不多，除了genDir，但不知为何生成文件的体积还是巨大。

**Comment by z827101859** [comment]
1、I use 'genDir' config in tsconfig.aot.json for [ngc-webpack] tool，if you use @ngtool/webpack，You do not need to set it，@ngtool/webpack will manage them in memory。
2、Contains all the core packets of the angular, after build with aot + ugily + tree-sharking，the lib.js is about 400kb, and after gip， it will be less than 100kb。so you said your compiled file is huge，how huge is it? I suggest you can check your related  angular lib references ,please dot put JiT complier in to lib.js（@angular/platform-browser-dynamic this is huge）。
3、any more question can also [wechat] me in private [ wechat id： sweetyx__x ]
-----------------------------翻译-----------------------------
1、我在tsconfig.aot.json中使用genDir配置主要是为了给ngc-webpack工具使用（在ngc-webpack.md有描述），如果你仅仅使用@ngtool/webpack工具，这个配置没有任何的影响。
2、包含angular所有核心包的js，在aot + ugily + tree-sharking之后在400kb多点，gip之后小于100kb ，所以你指的编译后的文件巨大是有多大？ 我建议你先检查下是不是把 JiT编译器也打包进了项目里（@angular/platform-browser-dynamic这个会非常大）。
3、如果你还有任何不明白的问题，也欢迎加我的微信，我会给你解答 [ 微信号： sweetyx__x ]

**Comment by keyiis** [comment]
@z827101859 谢谢回复！你说的第二种可能应该不会，因为关于aot的配置，和你差不多
我在angular-cli问过这个问题，但是也没有得到准确的解答，配置文件都写在里面了
https://github.com/angular/angular-cli/issues/4646#issuecomment-282311448
